INSERT INTO camisetas (tipo_camiseta, equipo, liga, dorsal, jugador, temporada, precio, tallas, marca, nombre, descripcion, imagen) VALUES ('EQUIPO', 'Deportes Temuco', 'Ascenso (Chile)', 10, '', '2015', '35000', 'M','ADIDAS', 'Deportes Temuco 2015', 'Camiseta Dep Temuco 2015', '')
INSERT INTO camisetas (tipo_camiseta, equipo, liga, dorsal, jugador, temporada, precio, tallas, marca, nombre, descripcion, imagen) VALUES ('EQUIPO', 'Borussia Dormunt', 'Bundesliga (Alemania)', 9, 'Earling Haaland', '2020', '50000', 'L','NIKE', 'Borussia Dormunt Haaland', 'Camiseta Haaland', '')
INSERT INTO camisetas (tipo_camiseta, equipo, liga, dorsal, jugador, temporada, precio, tallas, marca, nombre, descripcion, imagen) VALUES ('SELECCION', 'Francia', 'Mundial Rusia 2018', 10, 'Kylian Mbappé', '2018', '50000', 'L','NIKE', 'Francia 2018 Mbappé', 'Camiseta Mbappé', '')
INSERT INTO camisetas (tipo_camiseta, equipo, liga, dorsal, jugador, temporada, precio, tallas, marca, nombre, descripcion, imagen) VALUES ('SELECCION', 'Portugal', 'Clasificatorias', 7, 'Cristiano Ronaldo', '2020', '50000', 'S','NIKE', 'Portugal CR7', 'Camiseta Portugal CR7', '')
INSERT INTO camisetas (tipo_camiseta, equipo, liga, dorsal, jugador, temporada, precio, tallas, marca, nombre, descripcion, imagen) VALUES ('EQUIPO', 'Deportes Temuco', 'Ascenso (Chile)', 10, '', '2015', '35000', 'M','ADIDAS', 'Deportes Temuco 2015', 'Camiseta Dep Temuco 2015', '')
INSERT INTO camisetas (tipo_camiseta, equipo, liga, dorsal, jugador, temporada, precio, tallas, marca, nombre, descripcion, imagen) VALUES ('EQUIPO', 'Borussia Dormunt', 'Bundesliga (Alemania)', 9, 'Earling Haaland', '2020', '50000', 'L','NIKE', 'Borussia Dormunt Haaland', 'Camiseta Haaland', '')
INSERT INTO camisetas (tipo_camiseta, equipo, liga, dorsal, jugador, temporada, precio, tallas, marca, nombre, descripcion, imagen) VALUES ('SELECCION', 'Francia', 'Mundial Rusia 2018', 10, 'Kylian Mbappé', '2018', '50000', 'L','NIKE', 'Francia 2018 Mbappé', 'Camiseta Mbappé', '')
INSERT INTO camisetas (tipo_camiseta, equipo, liga, dorsal, jugador, temporada, precio, tallas, marca, nombre, descripcion, imagen) VALUES ('SELECCION', 'Portugal', 'Clasificatorias', 7, 'Cristiano Ronaldo', '2020', '50000', 'S','NIKE', 'Portugal CR7', 'Camiseta Portugal CR7', '')


